Cleanups

diff --git a/@ b/@
--- a/@
+++ b/@
@@ -187,11 +187,11 @@ var_exists () {
 }
 
 die () {
- echo "error: $1" ; exit 1
+ echo "error: $1" 1>&2 && exit 1
 }
 
 warn () {
- echo "warning: $1"
+ echo "warning: $1" 1>&2
 }
 
 main () {
